In [118]:
import pandas as pd
import os

fname = 'usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있다.
data.head(10)
data

user_id  \
0         00000c289a1829a808ac09c00daf10bc3c4e223b   
1         00000c289a1829a808ac09c00daf10bc3c4e223b   
2         00000c289a1829a808ac09c00daf10bc3c4e223b   
3         00000c289a1829a808ac09c00daf10bc3c4e223b   
4         00000c289a1829a808ac09c00daf10bc3c4e223b   
...                                            ...   
17535650                              sep 20, 2008   
17535651                              sep 20, 2008   
17535652                              sep 20, 2008   
17535653                              sep 20, 2008   
17535654                              sep 20, 2008   

                                   artist_MBID                artist  play  
0         3bd73256-3905-4f3a-97e2-8b341527f805       betty blowtorch  2137  
1         f2fb0ff0-5679-42ec-a55c-15109ce6e320             die Ärzte  1099  
2         b3ae82c2-e60b-4551-a76d-6620f1b456aa     melissa etheridge   897  
3         3d6bbeb7-f90e-4d10-b440-e153c0d10b53             elvenking   717  
4         bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8  juliette & the licks   706  
...                                        ...                   ...   ...  
17535650  7ffd711a-b34d-4739-8aab-25e045c246da            turbostaat    12  
17535651  9201190d-409f-426b-9339-9bd7492443e2         cuba missouri    11  
17535652  e7cf7ff9-ed2f-4315-aca8-bcbd3b2bfa71       little man tate    11  
17535653  f6f2326f-6b25-4170-b89d-e235b25508e8             sigur rós    10  
17535654  40f5d9e4-2de7-4f2d-ad41-e31a9a9fea27            the smiths    10  

[17535655 rows x 4 columns]

In [119]:
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [120]:
data['artist'] = data['artist'].str.lower()
data.head(10)

C:\Users\juwonhee\AppData\Local\Temp\ipykernel_13068\1588653435.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['artist'] = data['artist'].str.lower()


user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [121]:
condition = (data['user_id']== data.loc[0, 'user_id'])
data.loc[condition]

user_id                   artist  play
0   00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1   00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2   00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3   00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4   00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5   00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6   00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7   00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8   00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9   00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403
10  00000c289a1829a808ac09c00daf10bc3c4e223b         walls of jericho   393
11  00000c289a1829a808ac09c00daf10bc3c4e223b           letzte instanz   387
12  00000c289a1829a808ac09c00daf10bc3c4e223b                goldfrapp   361
13  00000c289a1829a808ac09c00daf10bc3c4e223b               horrorpops   358
14  00000c289a1829a808ac09c00daf10bc3c4e223b             the butchies   329
15  00000c289a1829a808ac09c00daf10bc3c4e223b            jack off jill   316
16  00000c289a1829a808ac09c00daf10bc3c4e223b         babes in toyland   310
17  00000c289a1829a808ac09c00daf10bc3c4e223b         dropkick murphys   302
18  00000c289a1829a808ac09c00daf10bc3c4e223b            all:my:faults   288
19  00000c289a1829a808ac09c00daf10bc3c4e223b                 le tigre   281
20  00000c289a1829a808ac09c00daf10bc3c4e223b               schandmaul   244
21  00000c289a1829a808ac09c00daf10bc3c4e223b                    edguy   232
22  00000c289a1829a808ac09c00daf10bc3c4e223b      maximum the hormone   231
23  00000c289a1829a808ac09c00daf10bc3c4e223b                 all ends   229
24  00000c289a1829a808ac09c00daf10bc3c4e223b             jack johnson   227
25  00000c289a1829a808ac09c00daf10bc3c4e223b                eluveitie   222
26  00000c289a1829a808ac09c00daf10bc3c4e223b                rasputina   220
27  00000c289a1829a808ac09c00daf10bc3c4e223b    london after midnight   210
28  00000c289a1829a808ac09c00daf10bc3c4e223b              the killers   208
29  00000c289a1829a808ac09c00daf10bc3c4e223b                  mutyumu   205
30  00000c289a1829a808ac09c00daf10bc3c4e223b             judas priest   198
31  00000c289a1829a808ac09c00daf10bc3c4e223b               rob zombie   198
32  00000c289a1829a808ac09c00daf10bc3c4e223b             the bosshoss   189
33  00000c289a1829a808ac09c00daf10bc3c4e223b         blue öyster cult   185
34  00000c289a1829a808ac09c00daf10bc3c4e223b             sandra nasic   183
35  00000c289a1829a808ac09c00daf10bc3c4e223b               john mayer   182
36  00000c289a1829a808ac09c00daf10bc3c4e223b           sleater-kinney   175
37  00000c289a1829a808ac09c00daf10bc3c4e223b                  the who   168
38  00000c289a1829a808ac09c00daf10bc3c4e223b                 disciple   154
39  00000c289a1829a808ac09c00daf10bc3c4e223b                  tanzwut   153
40  00000c289a1829a808ac09c00daf10bc3c4e223b               guano apes   151
41  00000c289a1829a808ac09c00daf10bc3c4e223b       the rolling stones   150
42  00000c289a1829a808ac09c00daf10bc3c4e223b          little big town   145
43  00000c289a1829a808ac09c00daf10bc3c4e223b              team dresch   137
44  00000c289a1829a808ac09c00daf10bc3c4e223b                    betty   135
45  00000c289a1829a808ac09c00daf10bc3c4e223b                       l7   135
46  00000c289a1829a808ac09c00daf10bc3c4e223b                bif naked   134
47  00000c289a1829a808ac09c00daf10bc3c4e223b               girlschool   134
48  00000c289a1829a808ac09c00daf10bc3c4e223b          the wallflowers   131

In [122]:
# 유저 수
data['user_id'].nunique()

358868

In [123]:
# 아티스트 수
data['artist'].nunique()

291346

In [124]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(30)

artist
radiohead                77254
the beatles              76245
coldplay                 66658
red hot chili peppers    48924
muse                     46954
metallica                45233
pink floyd               44443
the killers              41229
linkin park              39773
nirvana                  39479
system of a down         37267
queen                    34174
u2                       33206
daft punk                33001
the cure                 32624
led zeppelin             32295
placebo                  32072
depeche mode             31916
david bowie              31862
bob dylan                31799
death cab for cutie      31482
arctic monkeys           30348
foo fighters             30144
air                      29795
the rolling stones       29754
nine inch nails          28946
sigur rós                28901
green day                28732
massive attack           28691
moby                     28232
Name: user_id, dtype: int64

In [125]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

count    358868.000000
mean         48.863234
std           8.524272
min           1.000000
25%          46.000000
50%          49.000000
75%          51.000000
max         166.000000
Name: artist, dtype: float64

In [126]:
# 유저별 play횟수 중앙값에 대한 통계
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

count    358868.000000
mean        142.187676
std         213.089902
min           1.000000
25%          32.000000
50%          83.000000
75%         180.000000
max       50142.000000
Name: play, dtype: float64

In [127]:
my_favorite = ['halsey' , 'justin bieber' ,'one direction' ,'oasis' ,'taylor swift']

# 'wonhee'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정
my_playlist = pd.DataFrame({'user_id': ['zimin']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['zimin']})['user_id'].any():  # user_id에 'wonhee'이라는 데이터가 없다면
    data = pd.concat([data, my_playlist]) # 위에 임의로 만든 my_playlist 데이터를 추가

data.tail(10)       

user_id           artist  play
17535650  sep 20, 2008       turbostaat    12
17535651  sep 20, 2008    cuba missouri    11
17535652  sep 20, 2008  little man tate    11
17535653  sep 20, 2008        sigur rós    10
17535654  sep 20, 2008       the smiths    10
0                zimin           halsey    30
1                zimin    justin bieber    30
2                zimin    one direction    30
3                zimin            oasis    30
4                zimin     taylor swift    30

In [128]:
data = data.dropna()

In [129]:
data.isna().sum()

user_id    0
artist     0
play       0
dtype: int64

In [130]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [131]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해봄
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

user_id column indexing OK!!
artist column indexing OK!!


user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868  291346    30
1    358868  116391    30
2    358868  291347    30
3    358868     490    30
4    358868    7526    30

[17535456 rows x 3 columns]

In [132]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']==1]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

147736,17535456
Ratio of only_one over all data is 0.84%


In [133]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17535374 stored elements and shape (358869, 291348)>

In [134]:
csr_data.shape

(358869, 291348)

In [135]:
import sys
!{sys.executable} -m pip install implicit

In [136]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [137]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

In [138]:
# 모델 훈련
als_model.fit(csr_data)

  0%|          | 0/15 [00:00<?, ?it/s]

In [139]:
print("user_factors shape:", als_model.user_factors.shape)
print("item_factors shape:", als_model.item_factors.shape)

user_factors shape: (358869, 100)
item_factors shape: (291348, 100)


In [140]:
zimin, halsey = user_to_idx['zimin'], artist_to_idx['coldplay']
zimin_vector, halsey_vector = als_model.user_factors[wonhee], als_model.item_factors[halsey]

In [141]:
zimin_vector

array([ 2.1715624 , -3.3456995 ,  4.0172496 , -7.636756  , -4.031537  ,
        3.8317487 ,  7.5772486 , -1.7011445 ,  4.152123  ,  0.64166874,
        0.2922272 , -1.8926167 ,  0.20091733,  3.5280612 ,  0.8547094 ,
        4.2196193 , -1.5471694 ,  2.37811   ,  3.3685727 ,  3.5643969 ,
        2.8252902 ,  0.30173996, -0.9694518 , -5.8408475 , -2.2370622 ,
        4.134119  ,  4.1242704 , -2.55413   , -6.1944065 , -2.8481724 ,
        3.9390607 , -2.438441  ,  1.8405684 ,  0.17312431,  8.583645  ,
        2.7960525 ,  2.2013397 ,  7.567887  ,  0.1419304 , -0.46765336,
        4.44864   , -3.2801886 , -2.2057858 , -0.9650543 , -3.2227628 ,
        0.27100632,  2.70202   , -0.22299081, -3.0759146 , -4.7428527 ,
       -0.9741743 , -2.6291134 , -5.208213  ,  2.5060694 , -1.6806178 ,
       -3.161086  , -2.486722  , -6.103021  , -0.5800634 , -1.3623114 ,
       -2.6065276 ,  2.4179292 , -2.67884   ,  5.1429887 ,  0.04354278,
        2.878019  , -0.24230747, -3.3028913 , -0.9352479 , -1.87

In [142]:
halsey_vector

array([-6.5182557e-04,  9.7746421e-03,  2.6487164e-02, -3.6065516e-03,
        2.1834881e-03,  2.9820933e-03,  9.9337297e-03,  1.6252710e-03,
        1.7667245e-02,  1.1924072e-02,  1.7495003e-02,  1.3011534e-03,
        4.9024820e-03,  1.4844720e-02,  9.1024982e-03, -1.3808826e-03,
        8.2491990e-03,  4.4863471e-03,  1.8975671e-02,  2.3027664e-02,
        2.4590753e-02,  9.8068276e-03,  2.4694693e-03, -3.4938594e-03,
        3.3425328e-03,  6.8061338e-03,  9.0010772e-03, -1.3432984e-02,
        8.7915631e-03,  1.7837619e-02,  1.6080538e-02,  1.3591421e-02,
        1.2373922e-02,  1.0041600e-03,  8.6506559e-03, -8.3330357e-03,
        6.1610304e-03,  1.1745915e-02,  2.8052053e-03,  2.6601622e-02,
        3.7751733e-03,  2.3539022e-02, -8.3311563e-03,  8.6580971e-03,
       -2.9287683e-03, -8.7992903e-03,  5.9688240e-03,  3.4044583e-03,
       -1.4700235e-02, -2.4063749e-02,  1.1389113e-02, -4.1007791e-03,
        1.7296799e-02, -8.8535732e-04, -5.6169126e-03,  1.4786661e-03,
      

In [143]:
# zimin halsey를 내적하는 코드
np.dot(zimin_vector, halsey_vector)

1.0093262

In [144]:
justin_bieber = artist_to_idx['justin bieber']
justin_bieber_vector = als_model.item_factors[justin_bieber]
np.dot(zimin_vector, justin_bieber_vector)

-0.057508446

In [145]:
favorite_artist = 'justin bieber'
artist_id = artist_to_idx[favorite_artist]
similar_artist = als_model.similar_items(artist_id, N=15)
similar_artist

(array([116391,  44750, 126566,  80535,  53390, 123218, 144736, 212471,
         90283, 106350,  46133,  50891, 164529,  54407, 133650]),
 array([0.99999994, 0.98647475, 0.9863059 , 0.98613745, 0.98608816,
        0.9857092 , 0.98532283, 0.9849482 , 0.9849343 , 0.9843402 ,
        0.984326  , 0.98430693, 0.9841657 , 0.9840851 , 0.9838661 ],
       dtype=float32))

In [146]:
[idx_to_artist[i] for i in artist_recommended[0]]

[161,
 664,
 740,
 8688,
 4725,
 160,
 4479,
 1188,
 4947,
 7426,
 671,
 59,
 2116,
 2063,
 13989,
 1705,
 1708,
 302,
 1444,
 6611]

In [147]:
def get_similar_artist(artist_name: str):
    artist_id = artist_to_idx[artist_name]
    similar_artist = als_model.similar_items(artist_id)
    similar_artist = [idx_to_artist[i] for i in similar_artist[0]]
    return similar_artist

In [148]:
get_similar_artist('2pac')

[570, 3181, 562, 577, 597, 636, 557, 2727, 994, 561]

In [149]:
get_similar_artist('lady gaga')

[1800, 550, 350, 2249, 396, 618, 391, 358, 369, 354]

In [150]:
user = user_to_idx['zimin']
# recommend에서는 user*item CSR Matrix를 받는다.

# artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=False)
artist_recommended

(array([7526,   62,  247,  277,    5,  490,   28,  217,  418,  910,  694,
         473,  268,   75,  503,  969,  352,   55,  274,  782]),
 array([0.2805813 , 0.26256526, 0.25386953, 0.24787527, 0.2458687 ,
        0.24379928, 0.24336462, 0.23852302, 0.23701273, 0.23658884,
        0.22905296, 0.2284887 , 0.2235643 , 0.22231479, 0.22173084,
        0.21442749, 0.21129425, 0.21115808, 0.20211329, 0.20165633],
       dtype=float32))

In [151]:
[idx_to_artist[i] for i in artist_recommended[0]]

[7526,
 62,
 247,
 277,
 5,
 490,
 28,
 217,
 418,
 910,
 694,
 473,
 268,
 75,
 503,
 969,
 352,
 55,
 274,
 782]

In [154]:
rihanna = artist_to_idx['rihanna']
explain = als_model.explain(user, csr_data, itemid=rihanna)

In [1]:
#[(idx_to_artist[i[0]], i[1]) for i in explain[1]]